# ~/Repositories/config/ansible/playbooks/sync/config-sync.yml

- name: Sync Python configuration files from repository
  hosts: localhost
  gather_facts: true

  vars_files:
    - ~/Repositories/private/ansible/variables.yml
    
  tasks:
    - name: Sync Python scripts
      ansible.builtin.copy:
        src: "{{ config_repo }}/python/"
        dest: "{{ config_home }}/python/"
        mode: '0644'

    - name: Sync tmux configuration
      ansible.builtin.copy:
        src: "{{ config_repo }}/tmux/tmux.conf"
        dest: "{{ config_home }}/tmux/tmux.conf"
        mode: '0644'

    - name: Export ZSH plugins
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/plugins/"
        dest: "{{ config_home }}/zsh/plugins/"
        mode: '0644'

    - name: Export ZSH aliases
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/.aliases"
        dest: "{{ config_home }}/zsh/.aliases"
        mode: '0644'

    - name: Export ZSH configuration
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/.zshrc"
        dest: "{{ config_home }}/zsh/.zshrc"
        mode: '0644'

    - name: Export ZSH environment for server
      when: ansible_facts['os_family'] == "{{ server_system }}" 
      become: yes
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/zshenv"
        dest: /etc/zsh/zshenv
        owner: root
        mode: '0644'

    - name: Export ZSH environment for client (1)
      when: ansible_facts['distribution'] == "{{ client1_system }}"       
      become: yes
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/zshenv"
        dest: /etc/zshenv
        owner: root
        mode: '0644'