# ${XDG_CONFIG_HOME}/docker/docker-compose.yml

version: "3.9"
x-variables:
  production-standard: &production-standard
    init: true
    restart: ${RESTART}
    networks:
      production-network:
  env-standard: &env-standard
    PUID: ${PUID}
    PGID: ${PGID}
    TZ: ${TZ}

networks:
  production-network:
    name: production-network
    driver: bridge
  host-network:
    name: host
    external: true

services:
  vault:
    image: vault
    container_name: vault
#    volumes:
#      - ${CONFIG}/vault/logs:/vault/logs
#      - ${CONFIG}/vault/file:/vault/file
    environment:
#      << : *env-standard
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: my-token
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK