# ~/Repositories/config/ansible/playbooks/git-sync.yml

- name: Sync all Github repositories
  hosts: localhost

  vars_files:
    - ~/Repositories/private/variables/ansible-variables.yml

  tasks:
    - name: Pull config repository
      ansible.builtin.git:
        repo: "{{ config_repo_url }}"
        dest: "{{ config_repo }}"

    - name: Pull private repository
      ansible.builtin.git:
        repo: "{{ private_repo_url }}"
        dest: "{{ private_repo }}"