# ~/Repositories/config/ansible/playbooks/git-sync.yml

- hosts: localhost

  tasks:
    - name: Pull config repository
      git:
        repo: "{{ config_repo_url }}"
        dest: "{{ config_repo }}"

    - name: Pull private repository
      git:
        repo: "{{ private_repo_url }}"
        dest: "{{ private_repo }}"