# ${XDG_CONFIG_HOME}/ansible/playbooks/git-sync.yml

- hosts: local

  tasks:
   - name: find git directories
     find:
       paths: "{{ ansible_env.HOME }}/git"
       file_type: directory
     register: found_directories

   - name: pull latest changes
     shell: git pull 
     args:
       chdir: "{{ item.path }}"
       executable: /bin/bash
     with_items: "{{ found_directories.files }}"