# ~/Repositories/config/ansible/playbooks/git-sync.yml

- hosts: localhost
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  tasks:
    - name: find git directories
      find:
        paths: "{{ ansible_env.HOME }}/Repositories"
        file_type: directory
      register: found_directories

    - name: pull latest changes
      become: yes
      shell: git pull 
      args:
        chdir: "{{ item.path }}"
        executable: /bin/bash
      with_items: "{{ found_directories.files }}"