# ~/Repositories/config/ansible/playbooks/python-config.yml

- name: Export Python configuration files from repository
  hosts: localhost

  vars_files:
    - ~/Repositories/private/ansible/variables.yml
    
  tasks:
    - name: Export python scripts
      ansible.builtin.copy:
        src: "{{ config_repo }}/python/"
        dest: "{{ config_home }}/python/"
        mode: '0644'