# ~/Repositories/config/ansible/playbooks/tmux-config.yml

- name: Export tmux configuration files from repository
  hosts: localhost

  vars_files:
    - ~/Repositories/private/variables/ansible-variables.yml

  tasks:
    - name: Export tmux configuration
      ansible.builtin.copy:
        src: "{{ config_repo }}/tmux/tmux.conf"
        dest: "{{ config_home }}/tmux/tmux.conf"
        mode: '0644'

# Replace with path creation + git pull?
#   - name: Export tmux plugins
#     ansible.builtin.copy:
#       src: "{{ config_repo }}/tmux/plugins/"
#       dest: "{{ config_home }}/tmux/plugins/"
#       mode: '0644'