# zsh-config.yml

- name: Export ZSH configuration files from repository
  hosts: localhost
  connection: local
  become: yes
  gather_facts: true

  vars:
    config_repo: ~/Dropbox/Repositories/config
    config: ~/.config

  tasks:

    - name: Export ZSH plugins
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/plugins/"
        dest: "{{ config }}/zsh/plugins/"
        owner: bjanda
        mode: '0644'

    - name: Export ZSH dotfiles
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/.*"
        dest: "{{ config }}/zsh/"
        owner: bjanda
        mode: '0644'

    - name: Export ZSH environment for OSX
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/zshenv"
        dest: /etc/zshenv
        owner: root
        mode: '0644'
      when: ansible_facts['distribution'] == "MacOSX" 

    - name: Export ZSH environment for Ubuntu
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/zshenv"
        dest: /etc/zsh/zshenv
        owner: root
        mode: '0644'
      when: ansible_facts['distribution'] == "Ubuntu" 