# ${XDG_CONFIG_HOME}/ansible/playbooks/zsh-config.yml

- name: Export ZSH configuration files from repository
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    config_home: ${XDG_CONFIG_HOME}
    config_repo: ~/Dropbox/Repositories/config

  tasks:
    - name: Export ZSH plugins
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/plugins/"
        dest: "{{ config_home }}/zsh/plugins/"
        mode: '0644'

    - name: Export ZSH aliases
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/.aliases"
        dest: "{{ config_home }}/zsh/.aliases"
        mode: '0644'

    - name: Export ZSH configuration
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/.zshrc"
        dest: "{{ config_home }}/zsh/.zshrc"
        mode: '0644'

    - name: Export ZSH environment for OSX
      become: yes
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/zshenv"
        dest: /etc/zshenv
        owner: root
        mode: '0644'
      when: ansible_facts['distribution'] == "MacOSX" 

    - name: Export ZSH environment for Ubuntu
      become: yes
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/zshenv"
        dest: /etc/zsh/zshenv
        owner: root
        mode: '0644'
      when: ansible_facts['distribution'] == "Ubuntu" 