# ~/Repositories/config/ansible/playbooks/zsh-config.yml

- name: Export ZSH configuration files from repository
  hosts: localhost

  vars_files:
    - ~/Repositories/private/ansible/variables.yml

  tasks:
    - name: Export ZSH plugins
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/plugins/"
        dest: "{{ config_home }}/zsh/plugins/"
        mode: '0644'

    - name: Export ZSH aliases
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/.aliases"
        dest: "{{ config_home }}/zsh/.aliases"
        mode: '0644'

    - name: Export ZSH configuration
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/.zshrc"
        dest: "{{ config_home }}/zsh/.zshrc"
        mode: '0644'

    - name: Export ZSH environment for server
      become: yes
      gather_facts: true
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/zshenv"
        dest: /etc/zsh/zshenv
        owner: root
        mode: '0644'
      when: ansible_facts['os_family'] == "{{ server_system }}" 

    - name: Export ZSH environment for client 1
      become: yes
      gather_facts: true
      ansible.builtin.copy:
        src: "{{ config_repo }}/zsh/zshenv"
        dest: /etc/zshenv
        owner: root
        mode: '0644'
      when: ansible_facts['distribution'] == "{{ client1_system }}" 