# ~/Repositories/config/ansible/playbook-master.yml

- name: Master playbook
  hosts: localhost
  vars_files:
    - ~/Repositories/private/variables/ansible-variables.yml

- name: Pull all Github repositories
  import_playbook: playbooks/git-sync.yml

- name: Import all configuration
  import_playbook: 
    - playbooks/python-config.yml
    - playbooks/tmux-config.yml
    - playbooks/zsh-config.yml