# /etc/zsh/zshenv (Ubuntu)
# /etc/zshenv (OSX)

export DOCKER_CONFIG=$HOME/.docker
export REPOSITORIES=$HOME/Dropbox/Repositories
export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config

export ANSIBLE_CONFIG=$XDG_CONFIG_HOME/ansible
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export PYTHONSTARTUP=$XDG_CONFIG_HOME/python/pythonstartup.py

export COMPOSE_PUBLIC=$REPOSITORIES/config/
export COMPOSE_PRIVATE=$REPOSITORIES/private/

export LESSHISTFILE='-'
export HISTFILE=$ZDOTDIR/.zsh_history
export FZF_COMPLETION_TRIGGER='@@'
