# /etc/zsh/zshenv
export DOCKER_CONFIG=$HOME/.docker
export REPOSITORIES=$HOME/Dropbox/Repositories
export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config

export ANSIBLE_CONFIG=$XDG_CONFIG_HOME/ansible
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

export COMPOSE_PUBLIC=$REPOSITORIES/webserver-public/
export COMPOSE_TUNNELED=$REPOSITORIES/webserver-tunneled/

export LESSHISTFILE='-'
export FZF_COMPLETION_TRIGGER='@@'